name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: Test / OS ${{ matrix.os }} / Node ${{ matrix.node }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ['16']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install nhost CLI
        run: |
          curl -L https://raw.githubusercontent.com/nhost/cli/main/get.sh | bash

      - name: Run Nhost CLI
        run: |
          cd test/backend
          nhost dev -d
